# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 1337
  user_dir: ???
  empty_cache_freq: 10000

checkpoint:
  save_interval_updates: 5000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: uer



distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 8
  #distributed_port: 29671
  nprocs_per_node: 8

task:
  _name: av-roman-task
  is_s2s: false
  data: ???
  label_dir: ???
  labels: ["ltr"]
  sample_rate: 25
  max_sample_size: 600
  pad_audio: false
  random_crop: true
  normalize: true
  stack_order_audio: 4
  modalities: ["video", "audio"]
  image_aug: true
  noise_prob: 0.25
  noise_snr: 0
  noise_wav: ???


dataset:
  num_workers: 4
  max_tokens: 1000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 1
  train_subset: train
  valid_subset: test


criterion:
  _name: ctc
  zero_infinity: true
  # pred_masked_weight: 1.0
  # pred_nomask_weight: 1.0
  # loss_weights: [10,]

optimization:
  max_epoch: 15
  max_update: 200000
  lr: [3e-5]
  stop_min_lr: -1.0
  clip_norm: 10.0
  update_freq: [1]
  #sentence_avg: true

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  #init_lr_scale: 0.01 
  #final_lr_scale: 0.05 
  #warmup_updates: 48000

model:
  _name: av_romanizer
  w2v_path: ???
  avhubert_path: ???
  skip_masked: false
  skip_nomask: false
  modality_dropout: 0.5
  audio_dropout: 0.5
  modality_fuse: concat
  selection_type: same_seq
  masking_type: input
  mask_prob_image: 0.3
  mask_length_image: 5
  mask_prob_audio: 0.8
  mask_length_audio: 10
  extractor_mode: default
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 1.0
  activation_dropout: 0.0
  layer_norm_first: true
  encoder_layers: 24
  encoder_embed_dim: 1024


hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
